### ISSUE TITLE
mailinglist url incorrect

### ISSUE THREAD

**Issue by thijstriemstra** [gritzko/swift#3]
At the bottom of libswift.org there's a link to a mailinglist but it points to an email address (see doc/index.html).

**Comment by gritzko** [comment]
Please try http://listserv2.tudelft.nl/mailman/listinfo/swift-ewi

**Comment by thijstriemstra** [comment]
Thanks for your reply but that url doesn't resolve:

wget http://listserv2.tudelft.nl/mailman/listinfo/swift-ewi
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files\GnuWin32/etc/wgetrc
--2010-10-15 11:27:09--  http://listserv2.tudelft.nl/mailman/listinfo/swift-ewi
Resolving listserv2.tudelft.nl... 131.180.161.50
Connecting to listserv2.tudelft.nl|131.180.161.50|:80... failed: Network is unreachable.

**Comment by gritzko** [comment]
Sorry, https://listserv2.tudelft.nl/mailman/listinfo/swift-ewi
httpS only, admins are a bit too paranoid here...
